### PR TITLE
Add a comment to `region` attribute in `provider` definition

### PR DESCRIPTION
**Pull request by dhryniewicz**
For me personally it was surprising that the region is not taken from env variables first. IMHO it should at least be commented with a TODO or a FIXME.

### CODE REVIEW

**Review by jsyrjala — COMMENTED** [review]
What is the right env variable to look at?

**Comment by dhryniewicz** [comment]
`$AWS_DEFAULT_REGION`

**Comment by jsyrjala** [comment]
Thanks. I'll make it so that env variable is used and it defaults to 'eu-central-1'.

E.g. `${env:AWS_DEFAULT_REGION, 'eu-central-1'}`

**Comment by jsyrjala** [comment]
Closing this PR. Commit 0a9d36dfad1fe6023b2cc36334db954b0936022a adds support for AWS_DEFAULT_REGION.

**Comment by jsyrjala** [comment]
@werenall released 1.0.1 https://github.com/jsyrjala/aws-lambda-serverless/releases/tag/1.0.1 which includes AWS_DEFAULT_REGION support

**Pull request closed without merging**
